default: &default
  adapter: postgresql
  encoding: utf8
  pool: 40
  timeout: 5000
  database: todo
  username: postgres
  password: 192837465
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo
