source "https://rubygems.org"
gem "sinatra"
gem "puma"
gem "thin"
gem "falcon"
gem "webrick"
gem "pg"
gem "rake" 
gem "sinatra-activerecord" 
gem "validation_rules", "~> 1.0.5"
gem 'sinatra-flash', '~> 0.3.0'
gem 'bcrypt'
gem 'require_all'
